---
name: "🆗 Checksum"
on:
  push:
    paths:
      - "lib/sh/install_zpmod.sh"
      - "lib/sh/install.sh"
      - "lib/sh/sync-init.sh"
      - "lib/zsh/init.zsh"
      - ".github/workflows/checksum.yml"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  checksum:
    if: github.repository == 'z-shell/src'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "🆗 Generate checksum"
        uses: jmgilman/actions-generate-checksum@3ea6dc9bf8eecf28e2ecc982fab683484a1a8561 # v1.0.1
        with:
          patterns: |
            lib/sh/install_zpmod.sh
            lib/sh/install.sh
            lib/sh/sync-init.sh
            lib/zsh/init.zsh
      - run: mv checksum.txt lib/
      - name: "🆗 Commit"
        uses: z-shell/.github/actions/commit@d36763069484d7b5bf3d958e8517dbb682942c82 # v1.0.9
        with:
          commitMessage: Checksum ${{ github.sha }}
          workDir: lib
          commitUserName: ${{ secrets.ACTIONS_USER }}
          commitUserEmail: ${{ secrets.ACTIONS_MAIL }}
