---
name: "🔄 Rclone"
on:
  push:
    branches: [gh-pages]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    if: github.repository == 'z-shell/src'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      local_path: "."
      remote_path: "r2:r2-store/src"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: "⏫ Run rclone/r2-store"
        uses: z-shell/.github/actions/rclone@3222f53692e448ed6e2caf8b8722e74fb2ca2461 # v1.1.1
        with:
          config: ${{ secrets.R2_STORE }}
          args: "copy --check-first ${{ env.local_path }} ${{ env.remote_path }}"
          debug: false
